name: Publish Package

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
      - name: Set up Node.js & Update npm
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Node 22+ or 24 contains OIDC support
      - name: Upgrade npm CLI
        run: npm install -g npm@latest
      - run: bun i --frozen-lockfile --force
      - run: bun run build
      - run: bun run test
      - name: Publish to npm
        run: npm publish --provenance
